"""The grounded engine: false premises about real entities, anchored in the corpus itself.

The paper's second engine, and the one whose absence cost the most. Where the enumeration engine
needs a complete list of what exists in order to invent something that does not, this one needs no
list at all: it anchors on a fact the corpus states and twists the **datum**, leaving the entity's
name real. Nothing it emits claims an absence, so nothing it emits needs a boundary to stand behind
such a claim.

That is the whole reason it is the cheaper path (FR-042). A run against a corpus of ordinary words
had to supply a hand-written enumerator *and* a hand-written transformation; the enumerator is
irreducible, because completeness cannot be derived from a corpus, and the transformation was only
ever the stand-in for this engine.

**What it gives up.** It cannot test fabrication. ``doc = 0`` here means "the corpus does not say
this", asserted about a value rather than about a name, and ``absence_reliable`` is ``False`` on every
probe it produces because a passage is not a boundary (FR-023). An assistant that invents entities is
still the enumeration engine's business.

**What it costs.** One model call per passage per strategy. A corpus cut into forty passages against
five strategies is two hundred calls before the assistant is contacted once, which is why
``passages_per_strategy`` exists and why a run that bounds it is expected to say so.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from gaussia.core.probe_engine import ProbeEngine
from gaussia.schemas.roastme import KnowledgeHook, Probe

from .llm import DEFAULT_PASSAGE_CHARS, KEEP_REAL, passages
from .particularisation import domain_agnostic_probes, principle_by_plugin, strategy_attributes

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

    from gaussia.core.fact_twister import FactTwister
    from gaussia.schemas.roastme import Catalogue, Document, GroundedTwist, StrategySpec


class GroundedProbeEngine(ProbeEngine):
    """Probes whose false premise is a twisted fact of the corpus rather than an invented entity.

    Args:
        twister: How a passage becomes a false premise. Required, and the only path to the corpus this
            engine has — the same shape of dependency ``EnumerationProbeEngine`` has on its
            enumerator, so an engine that cannot produce a premise never comes into existence.
        entity_kinds: The ``StrategySpec.entity_kind`` values this engine is being trusted with.
            Declared rather than inferred, because the kind is the user's own vocabulary and catalogue
            validation needs it declared before a typo can be caught (FR-025). Empty is unrestricted,
            which is the default and what a user who named no kind asked for.
        passage_chars: How much corpus goes into one request.
        passages_per_strategy: How many passages each strategy draws on, or ``None`` for all of them.
            A cap on cost, and the honest kind: it takes the *first* n passages in document order
            rather than sampling, so what a bounded run covered is stated by the number rather than
            hidden by it.

    Every probe records the twister's model on ``Probe.model`` (FR-046), so a probe set generated by
    one model is never mistaken for one generated by another.
    """

    def __init__(
        self,
        twister: FactTwister,
        entity_kinds: Iterable[str] = (),
        passage_chars: int = DEFAULT_PASSAGE_CHARS,
        passages_per_strategy: int | None = None,
    ) -> None:
        self._twister = twister
        self._entity_kinds = frozenset(entity_kinds)
        self._passage_chars = passage_chars
        self._passages_per_strategy = passages_per_strategy

    @property
    def name(self) -> str:
        return "grounded"

    @property
    def entity_kinds(self) -> frozenset[str]:
        return self._entity_kinds

    @property
    def twister(self) -> FactTwister:
        """Recorded for reading, so a report can say which construction produced a probe."""
        return self._twister

    def can_handle(self, document: Document) -> bool:
        """Any document is prose a twister can anchor in.

        Unlike the enumeration engine, it does not ask for ``structured``: that field says whether a
        document's boundary can be enumerated, and this engine establishes no boundary. Declining an
        unstructured document would decline exactly the corpus this engine exists for.
        """
        return True

    def generate(self, documents: list[Document], catalogue: Catalogue) -> list[Probe]:
        if not documents:
            return domain_agnostic_probes(catalogue, self.name, self._handles)
        cut = list(passages(documents, self._passage_chars))
        if self._passages_per_strategy is not None:
            cut = cut[: self._passages_per_strategy]
        principles = principle_by_plugin(catalogue)
        return [
            probe
            for strategy in catalogue.strategies
            if self._handles(strategy.entity_kind)
            for probe in self._probes_for(strategy, cut, principles)
        ]

    def _handles(self, kind: str) -> bool:
        return not self._entity_kinds or kind in self._entity_kinds

    def _probes_for(
        self,
        strategy: StrategySpec,
        cut: Sequence[tuple[str, str]],
        principles: dict[str, str],
    ) -> list[Probe]:
        principle = principles[strategy.plugin] if strategy.plugin is not None else None
        probes: list[Probe] = []
        for _, passage in cut:
            twist = self._twister.twist(passage, strategy.transform, strategy.entity_kind, strategy.phrasing_hint)
            # A passage that yields no twist yields no probe, and the index moves on. Numbering by
            # the probes produced rather than by the passages tried keeps identifiers contiguous,
            # and how many passages were skipped is a property of the run rather than of a probe.
            if twist is not None:
                probes.append(self._build(strategy, principle, twist, len(probes)))
        return probes

    def _build(
        self,
        strategy: StrategySpec,
        principle: str | None,
        twist: GroundedTwist,
        index: int,
    ) -> Probe:
        # `keep_real` is the control: the premise is the fact untouched, so the label is documented
        # and the meta carries no `false_value`. A grader's rubric reads the absence of that key as
        # "nothing false was asserted", which is what makes a control gradeable against the same
        # rubric as an attack instead of needing one of its own.
        control = strategy.transform == KEEP_REAL
        premise = twist.real_fact if control else twist.false_premise
        meta = {"real_value": twist.real_fact}
        if not control:
            meta["false_value"] = twist.false_premise
        return Probe(
            id=f"{self.name}-{strategy.id}-{index}",
            query=twist.query,
            hook=KnowledgeHook(
                kind=strategy.entity_kind,
                references=premise,
                doc=int(control),
                how=twist.pattern,
                base_entity=twist.entity if not control else None,
                principle=principle,
                # FR-023. A passage is a sample of the corpus and never the whole of it, so this
                # engine can no more confirm that the corpus omits a value than a similarity search
                # can confirm it omits an entity. The label stands as a claim; nobody checked it.
                absence_reliable=control,
            ),
            plugin=strategy.plugin,
            strategy=strategy.id,
            attrs=strategy_attributes(strategy),
            engine=self.name,
            model=self._twister.model,
            meta=meta,
        )
